version: '3'
services:

  frontend:
    image: obrienpja/qspice-app:1.0
    container_name: frontend-main-container
    ports:
      - 3000:3000
    environment:
      - NEXT_PUBLIC_API_URL:localhost:5000

  backend:
    image: obrienpja/qspice-backend:1.0 
    container_name: backend-connor-sweeping-container
    ports:
      - 5000:5000
