version: '3'
services:

  frontend:
    image: frontend-main:latest
    container_name: frontend-main-container
    ports:
      - 3000:3000
    environment:
      - NEXT_PUBLIC_API_URL:localhost:5000

  backend:
    image: backend-connor-sweeping:latest
    container_name: backend-connor-sweeping-container
    ports:
      - 5000:5000
